config/routes.rb
Rails.application.routes.draw do

  resources :match_events

  resources :events

  resources :user_place_category_matches

  resources :user_place_categories
    post '/user_place_categories', to: 'user_place_categories#create', defaults: { format: 'json'}

  resources :matches
    get '/grab', to: 'matches#grab', defaults: { format: 'json'}

  resources :user_places
    post '/user_places', to: 'user_places#create', defaults: { format: 'json'}

  resources :photos

  resources :places
    get '/yelp_api_search', to: 'places#yelp_search', defaults: { format: 'json'}

  resources :users
    get '/user_search', to: 'users#user_search', defaults: { format: 'json'}
    get '/users/:id/setup', to: 'users#setup'

  get '/login', to: 'sessions#new', as: :login
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  get '/logout', to: 'sessions#destroy'

end

app/models/user_place.rb
class UserPlace < ActiveRecord::Base
	belongs_to :users, :class_name => 'User', :foreign_key => "user_id"
	has_many :user_place_categories, :class_name => 'UserPlaceCategory', :foreign_key => "userplace_id"
end

app/controllers/user_places_controller.rb
class UserPlacesController < ApplicationController
  before_action :set_user_place, only: [:show, :edit, :update, :destroy]

  # GET /user_places
  # GET /user_places.json
  def index
    @user_places = UserPlace.all
  end

  # GET /user_places/1
  # GET /user_places/1.json
  def show
  end

  # GET /user_places/new
  def new
    @user_place = UserPlace.new
  end

  # GET /user_places/1/edit
  def edit
  end

  # POST /user_places
  # POST /user_places.json
  def create
    @user_place = UserPlace.new(user_place_params)

    respond_to do |format|
      if @user_place.save
        format.html { redirect_to @user_place, notice: 'User place was successfully created.' }
        format.json { render json: @user_place }
      else
        format.html { render :new }
        format.json { render json: @user_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_places/1
  # PATCH/PUT /user_places/1.json
  def update
    respond_to do |format|
      if @user_place.update(user_place_params)
        format.html { redirect_to @user_place, notice: 'User place was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_place }
      else
        format.html { render :edit }
        format.json { render json: @user_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_places/1
  # DELETE /user_places/1.json
  def destroy
    @user_place.destroy
    respond_to do |format|
      format.html { redirect_to user_places_url, notice: 'User place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_place
      @user_place = UserPlace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_place_params
      params.require(:user_place).permit(:user_id, :place, :desc)
    end
end

app/helpers/user_places_helper.rb
module UserPlacesHelper
end

app/views/user_places/_form.html.erb
<%= form_for(@user_place) do |f| %>
  <% if @user_place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_place.errors.count, "error") %> prohibited this user_place from being saved:</h2>

      <ul>
      <% @user_place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_places/edit.html.erb
<h1>Editing User Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_place %> |
<%= link_to 'Back', user_places_path %>

app/views/user_places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Places</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Place</th>
      <th>Desc</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_places.each do |user_place| %>
      <tr>
        <td><%= user_place.user_id %></td>
        <td><%= user_place.place_id %></td>
        <td><%= user_place.desc %></td>
        <td><%= user_place.rating %></td>
        <td><%= link_to 'Show', user_place %></td>
        <td><%= link_to 'Edit', edit_user_place_path(user_place) %></td>
        <td><%= link_to 'Destroy', user_place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User place', new_user_place_path %>

app/views/user_places/new.html.erb
<h1>New User Place</h1>

<%= render 'form' %>

<%= link_to 'Back', user_places_path %>

app/views/user_places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_place.user_id %>
</p>

<p>
  <strong>Place:</strong>
  <%= @user_place.place %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @user_place.desc %>
</p>

<%= link_to 'Edit', edit_user_place_path(@user_place) %> |
<%= link_to 'Back', user_places_path %>