config/routes.rb
Rails.application.routes.draw do

  resources :match_events

  resources :events

  resources :user_place_category_matches

  resources :user_place_categories
    post '/user_place_categories', to: 'user_place_categories#create', defaults: { format: 'json'}

  resources :matches
    get '/grab', to: 'matches#grab', defaults: { format: 'json'}

  resources :user_places
    post '/user_places', to: 'user_places#create', defaults: { format: 'json'}

  resources :photos

  resources :places
    get '/yelp_api_search', to: 'places#yelp_search', defaults: { format: 'json'}

  resources :users
    get '/user_search', to: 'users#user_search', defaults: { format: 'json'}
    get '/users/:id/setup', to: 'users#setup'

  get '/login', to: 'sessions#new', as: :login
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  get '/logout', to: 'sessions#destroy'

end

app/models/user_place_category_match.rb
class UserPlaceCategoryMatch < ActiveRecord::Base
	belongs_to :matches
	belongs_to :user_place_categories
end

app/controllers/user_place_category_matches_controller.rb
class UserPlaceCategoryMatchesController < ApplicationController
  before_action :set_user_place_category_match, only: [:show, :edit, :update, :destroy]

  # GET /user_place_category_matches
  # GET /user_place_category_matches.json
  def index
    @user_place_category_matches = UserPlaceCategoryMatch.all
  end

  # GET /user_place_category_matches/1
  # GET /user_place_category_matches/1.json
  def show
  end

  # GET /user_place_category_matches/new
  def new
    @user_place_category_match = UserPlaceCategoryMatch.new
  end

  # GET /user_place_category_matches/1/edit
  def edit
  end

  # POST /user_place_category_matches
  # POST /user_place_category_matches.json
  def create
    @user_place_category_match = UserPlaceCategoryMatch.new(user_place_category_match_params)

    respond_to do |format|
      if @user_place_category_match.save
        format.html { redirect_to @user_place_category_match, notice: 'User place category match was successfully created.' }
        format.json { render :show, status: :created, location: @user_place_category_match }
      else
        format.html { render :new }
        format.json { render json: @user_place_category_match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_place_category_matches/1
  # PATCH/PUT /user_place_category_matches/1.json
  def update
    respond_to do |format|
      if @user_place_category_match.update(user_place_category_match_params)
        format.html { redirect_to @user_place_category_match, notice: 'User place category match was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_place_category_match }
      else
        format.html { render :edit }
        format.json { render json: @user_place_category_match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_place_category_matches/1
  # DELETE /user_place_category_matches/1.json
  def destroy
    @user_place_category_match.destroy
    respond_to do |format|
      format.html { redirect_to user_place_category_matches_url, notice: 'User place category match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_place_category_match
      @user_place_category_match = UserPlaceCategoryMatch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_place_category_match_params
      params.require(:user_place_category_match).permit(:match_id, :upc_id)
    end
end

app/helpers/user_place_category_matches_helper.rb
module UserPlaceCategoryMatchesHelper
end

app/views/user_place_category_matches/_form.html.erb
<%= form_for(@user_place_category_match) do |f| %>
  <% if @user_place_category_match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_place_category_match.errors.count, "error") %> prohibited this user_place_category_match from being saved:</h2>

      <ul>
      <% @user_place_category_match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :match_id %><br>
    <%= f.number_field :match_id %>
  </div>
  <div class="field">
    <%= f.label :upc_id %><br>
    <%= f.number_field :upc_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_place_category_matches/edit.html.erb
<h1>Editing User Place Category Match</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_place_category_match %> |
<%= link_to 'Back', user_place_category_matches_path %>

app/views/user_place_category_matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Place Category Matches</h1>

<table>
  <thead>
    <tr>
      <th>Match</th>
      <th>Upc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_place_category_matches.each do |user_place_category_match| %>
      <tr>
        <td><%= user_place_category_match.match_id %></td>
        <td><%= user_place_category_match.upc_id %></td>
        <td><%= link_to 'Show', user_place_category_match %></td>
        <td><%= link_to 'Edit', edit_user_place_category_match_path(user_place_category_match) %></td>
        <td><%= link_to 'Destroy', user_place_category_match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User place category match', new_user_place_category_match_path %>

app/views/user_place_category_matches/new.html.erb
<h1>New User Place Category Match</h1>

<%= render 'form' %>

<%= link_to 'Back', user_place_category_matches_path %>

app/views/user_place_category_matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Match:</strong>
  <%= @user_place_category_match.match_id %>
</p>

<p>
  <strong>Upc:</strong>
  <%= @user_place_category_match.upc_id %>
</p>

<%= link_to 'Edit', edit_user_place_category_match_path(@user_place_category_match) %> |
<%= link_to 'Back', user_place_category_matches_path %>