config/routes.rb
Rails.application.routes.draw do

  resources :match_events

  resources :events

  resources :user_place_category_matches

  resources :user_place_categories
    post '/user_place_categories', to: 'user_place_categories#create', defaults: { format: 'json'}

  resources :matches
    get '/grab', to: 'matches#grab', defaults: { format: 'json'}

  resources :user_places
    post '/user_places', to: 'user_places#create', defaults: { format: 'json'}

  resources :photos

  resources :places
    get '/yelp_api_search', to: 'places#yelp_search', defaults: { format: 'json'}

  resources :users
    get '/user_search', to: 'users#user_search', defaults: { format: 'json'}
    get '/users/:id/setup', to: 'users#setup'

  get '/login', to: 'sessions#new', as: :login
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  get '/logout', to: 'sessions#destroy'

end

app/models/user_place_category.rb
class UserPlaceCategory < ActiveRecord::Base
	belongs_to :user_places, :class_name => 'UserPlace', :foreign_key => 'userplace_id'
end

app/controllers/user_place_categories_controller.rb
class UserPlaceCategoriesController < ApplicationController
  before_action :set_user_place_category, only: [:show, :edit, :update, :destroy]

  # GET /user_place_categories
  # GET /user_place_categories.json
  def index
    @user_place_categories = UserPlaceCategory.all
  end

  # GET /user_place_categories/1
  # GET /user_place_categories/1.json
  def show
  end

  # GET /user_place_categories/new
  def new
    @user_place_category = UserPlaceCategory.new
  end

  # GET /user_place_categories/1/edit
  def edit
  end

  # POST /user_place_categories
  # POST /user_place_categories.json
  def create
    @user_place_category = UserPlaceCategory.new(user_place_category_params)

    respond_to do |format|
      if @user_place_category.save
        format.html { redirect_to @user_place_category, notice: 'User place category was successfully created.' }
        format.json { render json: @user_place_category }
      else
        format.html { render :new }
        format.json { render json: @user_place_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_place_categories/1
  # PATCH/PUT /user_place_categories/1.json
  def update
    respond_to do |format|
      if @user_place_category.update(user_place_category_params)
        format.html { redirect_to @user_place_category, notice: 'User place category was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_place_category }
      else
        format.html { render :edit }
        format.json { render json: @user_place_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_place_categories/1
  # DELETE /user_place_categories/1.json
  def destroy
    @user_place_category.destroy
    respond_to do |format|
      format.html { redirect_to user_place_categories_url, notice: 'User place category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_place_category
      @user_place_category = UserPlaceCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_place_category_params
      params.require(:user_place_category).permit(:userplace_id, :category)
    end
end

app/helpers/user_place_categories_helper.rb
module UserPlaceCategoriesHelper
end

app/views/user_place_categories/_form.html.erb
<%= form_for(@user_place_category) do |f| %>
  <% if @user_place_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_place_category.errors.count, "error") %> prohibited this user_place_category from being saved:</h2>

      <ul>
      <% @user_place_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userplace_id %><br>
    <%= f.number_field :userplace_id %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.number_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_place_categories/edit.html.erb
<h1>Editing User Place Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_place_category %> |
<%= link_to 'Back', user_place_categories_path %>

app/views/user_place_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Place Categories</h1>

<table>
  <thead>
    <tr>
      <th>Userplace</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_place_categories.each do |user_place_category| %>
      <tr>
        <td><%= user_place_category.userplace_id %></td>
        <td><%= user_place_category.category %></td>
        <td><%= link_to 'Show', user_place_category %></td>
        <td><%= link_to 'Edit', edit_user_place_category_path(user_place_category) %></td>
        <td><%= link_to 'Destroy', user_place_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User place category', new_user_place_category_path %>

app/views/user_place_categories/new.html.erb
<h1>New User Place Category</h1>

<%= render 'form' %>

<%= link_to 'Back', user_place_categories_path %>

app/views/user_place_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userplace:</strong>
  <%= @user_place_category.userplace_id %>
</p>

<p>
  <strong>Placecat:</strong>
  <%= @user_place_category.category %>
</p>

<%= link_to 'Edit', edit_user_place_category_path(@user_place_category) %> |
<%= link_to 'Back', user_place_categories_path %>