config/routes.rb
Rails.application.routes.draw do

  resources :match_events

  resources :events

  resources :user_place_category_matches

  resources :user_place_categories
    post '/user_place_categories', to: 'user_place_categories#create', defaults: { format: 'json'}

  resources :matches
    get '/grab', to: 'matches#grab', defaults: { format: 'json'}

  resources :user_places
    post '/user_places', to: 'user_places#create', defaults: { format: 'json'}

  resources :photos

  resources :places
    get '/yelp_api_search', to: 'places#yelp_search', defaults: { format: 'json'}

  resources :users
    get '/user_search', to: 'users#user_search', defaults: { format: 'json'}
    get '/users/:id/setup', to: 'users#setup'

  get '/login', to: 'sessions#new', as: :login
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  get '/logout', to: 'sessions#destroy'

end

app/models/match_event.rb
class MatchEvent < ActiveRecord::Base
	belongs_to :matches
	belongs_to :events
end

app/controllers/match_events_controller.rb
class MatchEventsController < ApplicationController
  before_action :set_match_event, only: [:show, :edit, :update, :destroy]

  # GET /match_events
  # GET /match_events.json
  def index
    @match_events = MatchEvent.all
  end

  # GET /match_events/1
  # GET /match_events/1.json
  def show
  end

  # GET /match_events/new
  def new
    @match_event = MatchEvent.new
  end

  # GET /match_events/1/edit
  def edit
  end

  # POST /match_events
  # POST /match_events.json
  def create
    @match_event = MatchEvent.new(match_event_params)

    respond_to do |format|
      if @match_event.save
        format.html { redirect_to @match_event, notice: 'Match event was successfully created.' }
        format.json { render :show, status: :created, location: @match_event }
      else
        format.html { render :new }
        format.json { render json: @match_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /match_events/1
  # PATCH/PUT /match_events/1.json
  def update
    respond_to do |format|
      if @match_event.update(match_event_params)
        format.html { redirect_to @match_event, notice: 'Match event was successfully updated.' }
        format.json { render :show, status: :ok, location: @match_event }
      else
        format.html { render :edit }
        format.json { render json: @match_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /match_events/1
  # DELETE /match_events/1.json
  def destroy
    @match_event.destroy
    respond_to do |format|
      format.html { redirect_to match_events_url, notice: 'Match event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match_event
      @match_event = MatchEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_event_params
      params.require(:match_event).permit(:match_id, :event_id)
    end
end

app/helpers/match_events_helper.rb
module MatchEventsHelper
end

app/views/match_events/_form.html.erb
<%= form_for(@match_event) do |f| %>
  <% if @match_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match_event.errors.count, "error") %> prohibited this match_event from being saved:</h2>

      <ul>
      <% @match_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :match_id %><br>
    <%= f.number_field :match_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.number_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/match_events/edit.html.erb
<h1>Editing Match Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @match_event %> |
<%= link_to 'Back', match_events_path %>

app/views/match_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Match Events</h1>

<table>
  <thead>
    <tr>
      <th>Match</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @match_events.each do |match_event| %>
      <tr>
        <td><%= match_event.match_id %></td>
        <td><%= match_event.event_id %></td>
        <td><%= link_to 'Show', match_event %></td>
        <td><%= link_to 'Edit', edit_match_event_path(match_event) %></td>
        <td><%= link_to 'Destroy', match_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match event', new_match_event_path %>

app/views/match_events/new.html.erb
<h1>New Match Event</h1>

<%= render 'form' %>

<%= link_to 'Back', match_events_path %>

app/views/match_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Match:</strong>
  <%= @match_event.match_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @match_event.event_id %>
</p>

<%= link_to 'Edit', edit_match_event_path(@match_event) %> |
<%= link_to 'Back', match_events_path %>